---
- name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresql57cis_rule_1_1_id }} | Reset Rule Result to default value"
  ansible.builtin.set_fact:
    postgresql57cis_rule_result: "FAILED"

- name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresql57cis_rule_1_1_id }} | Set Fact Rule ID"
  ansible.builtin.set_fact:
    postgresql_cis_rule_id: "{{ postgresql57cis_rule_1_1_id | default('Missing Rule ID') }}"

- name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresql57cis_rule_1_1_id }} | Set Fact Rule Name"
  ansible.builtin.set_fact:
    postgresql_cis_rule_name: "{{ postgresql57cis_rule_1_1_name }}"

- name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresql57cis_rule_1_1_id }} | AUDIT | {{ postgresql_cis_rule_name }}"
  tags:
    - audit
    - level1-postgresql
    - rule_1.1
  when:
    - postgresql57cis_rule_1_1
  block: