- name: "Include Section 1 Tasks"
  ansible.builtin.include_tasks: postgresql/section_1/main.yml
  when:
    - postgresqlcis_section_1
  tags:
    - postgresqlcis_section_1


- name: "Include Section 2 Tasks"
  ansible.builtin.include_tasks: postgresql/section_2/main.yml
  when:
    - postgresqlcis_section_2
  tags:
    - postgresqlcis_section_2

- name: "Include Section 3 Tasks"
  ansible.builtin.include_tasks: 
    file: postgresql/section_3/main.yml
    apply:
      tags: audit
  when:
    - postgresqlcis_section_3
  tags:
    - postgresqlcis_section_3
    - audit
  

- name: "Include Section 4 Tasks"
  ansible.builtin.include_tasks: postgresql/section_4/main.yml
  when:
    - postgresqlcis_section_4
  tags:
    - postgresqlcis_section_4

- name: "Include Section 5 Tasks"
  ansible.builtin.include_tasks: postgresql/section_5/main.yml
  when:
    - postgresqlcis_section_5
  tags:
    - postgresqlcis_section_5

- name: "Include Section 6 Tasks"
  ansible.builtin.include_tasks: postgresql/section_6/main.yml
  when:
    - postgresqlcis_section_6
  tags:
    - postgresqlcis_section_6

- name: "Include Section 7 Tasks"
  ansible.builtin.include_tasks: postgresql/section_7/main.yml
  when:
    - postgresqlcis_section_7
  tags:
    - postgresqlcis_section_7

- name: "Include Section 8 Tasks"
  ansible.builtin.include_tasks: postgresql/section_8/main.yml
  when:
    - postgresqlcis_section_8
  tags:
    - postgresqlcis_section_8
