---
- name: "SECTION | {{ postgresqlcis_rule_5_1_id }} | {{ postgresqlcis_rule_5_1_name }}"
  ansible.builtin.include_tasks: cis_5.1.yml
  vars:
    postgresqlcis_rule_5_1_name: ""
  when:
    - postgresqlcis_rule_5_1
  tags:
    - postgresqlcis_rule_5_1

- name: "SECTION | {{ postgresqlcis_rule_5_2_id }} | {{ postgresqlcis_rule_5_2_name }}"
  ansible.builtin.include_tasks: cis_5.2.yml
  vars:
    postgresqlcis_rule_5_2_name: ""
  when:
    - postgresqlcis_rule_5_2
  tags:
    - postgresqlcis_rule_5_2
...
