---
- name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresqlcis_rule_3_1_3_id }}"
  tags:
    - always
  when:
    - postgresqlcis_rule_3_1_3
  block:
    - name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresqlcis_rule_3_1_3_id }} | Reset Rule Result to default value"
      ansible.builtin.set_fact:
        postgresqlcis_rule_result: "FAILED"      

    - name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresqlcis_rule_3_1_3_id }} | Set Fact Rule ID"
      ansible.builtin.set_fact:
        postgresql_cis_rule_id: "{{ postgresqlcis_rule_3_1_3_id | default('Missing Rule ID') }}"

    - name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresqlcis_rule_3_1_3_id }} | Set Fact Rule Name"
      ansible.builtin.set_fact:
        postgresql_cis_rule_name: "{{ postgresqlcis_rule_3_1_3_name }}"

- name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresqlcis_rule_3_1_3_id }} | AUDIT | {{ postgresql_cis_rule_name }}"
  tags:
    - audit
  when:
    - postgresqlcis_rule_3_1_3
  block:
    - name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresqlcis_rule_3_1_2_id }} | AUDIT | {{ postgresql_cis_rule_name }} | Query Logging Collector"
      community.postgresql.postgresql_query:
        query:
          - SHOW logging_collector
      register: postgresqlcis_rule_3_1_3_results
      delegate_to: localhost

    - name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresqlcis_rule_3_1_3_id }} | AUDIT | {{ postgresql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        postgresqlcis_rule_result: "PASSED"
      when: postgresqlcis_rule_3_1_3_results['query_result'] | selectattr('logging_collector', 'equalto', postgresqlcis_logging_collector)
    
    - name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresqlcis_rule_3_1_3_id }} | AUDIT | {{ postgresql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        postgresql_cis_rule_result: "{{ postgresqlcis_rule_result }}"

    - name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresqlcis_rule_3_1_3_id }} | AUDIT | {{ postgresql_cis_rule_name }} | Add {{ postgresql_cis_rule_id }} result to WARNING Report"
      ansible.builtin.include_tasks:
        file: warning-audit-report.yml
      when: not postgresqlcis_rule_3_1_3_results['query_result'] | selectattr('logging_collector', 'equalto', postgresqlcis_logging_collector) 

    - name: "PostgreSQL {{ postgresql_ver_full }} CIS {{ postgresqlcis_rule_3_1_3_id }} | AUDIT | {{ postgresql_cis_rule_name }} | Add {{ postgresql_cis_rule_id }} result to FULL Report"
      ansible.builtin.include_tasks:
        file: full-audit-report.yml 
...
