---
- name: "SECTION | {{ postgresqlcis_rule_3_1_1_id }} | {{ postgresqlcis_rule_3_1_1_name }}"
  ansible.builtin.include_tasks: cis_3.1.1.yml
  vars:
    postgresqlcis_rule_3_1_1_name: ""
  when:
    - postgresqlcis_rule_3_1_1
  tags:    
    - postgresqlcis_rule_3_1_1

- name: "SECTION | {{ postgresqlcis_rule_3_1_2_id }} | {{ postgresqlcis_rule_3_1_2_name }}"
  ansible.builtin.include_tasks: cis_3.1.2.yml
  vars:
    postgresqlcis_rule_3_1_2_name: "Ensure the log destinations are set correctly"
  when:
    - postgresqlcis_rule_3_1_2
  tags:  
    - postgresqlcis_rule_3_1_2
    - level1-postgresql

- name: "SECTION | {{ postgresqlcis_rule_3_1_3_id }} | {{ postgresqlcis_rule_3_1_3_name }}"
  ansible.builtin.include_tasks: cis_3.1.3.yml
  vars:
    postgresqlcis_rule_3_1_3_name: "Ensure the logging collector is enabled"
  when:
    - postgresqlcis_rule_3_1_3
  tags:
    - postgresqlcis_rule_3_1_3

- name: "SECTION | {{ postgresqlcis_rule_3_1_4_id }} | {{ postgresqlcis_rule_3_1_4_name }}"
  ansible.builtin.include_tasks: cis_3.1.4.yml
  vars:
    postgresqlcis_rule_3_1_4_name: ""
  when:
    - postgresqlcis_rule_3_1_4
  tags:
    - postgresqlcis_rule_3_1_4

- name: "SECTION | {{ postgresqlcis_rule_3_1_5_id }} | {{ postgresqlcis_rule_3_1_5_name }}"
  ansible.builtin.include_tasks: cis_3.1.5.yml
  vars:
    postgresqlcis_rule_3_1_5_name: "Ensure the filename pattern for log files is set correctly"
  when:
    - postgresqlcis_rule_3_1_5
  tags:
    - postgresqlcis_rule_3_1_5
    - level1-postgresql

- name: "SECTION | {{ postgresqlcis_rule_3_1_6_id }} | {{ postgresqlcis_rule_3_1_6_name }}"
  ansible.builtin.include_tasks: cis_3.1.6.yml
  vars:
    postgresqlcis_rule_3_1_6_name: "Ensure the log file permissions are set correctly"
  when:
    - postgresqlcis_rule_3_1_6
  tags:
    - postgresqlcis_rule_3_1_6

- name: "SECTION | {{ postgresqlcis_rule_3_1_7_id }} | {{ postgresqlcis_rule_3_1_7_name }}"
  ansible.builtin.include_tasks: cis_3.1.7.yml
  vars:
    postgresqlcis_rule_3_1_7_name: "Ensure 'log_truncate_on_rotation' is enabled"
  when:
    - postgresqlcis_rule_3_1_7
  tags:
    - postgresqlcis_rule_3_1_7

- name: "SECTION | {{ postgresqlcis_rule_3_1_8_id }} | {{ postgresqlcis_rule_3_1_8_name }}"
  ansible.builtin.include_tasks: cis_3.1.8.yml
  vars:
    postgresqlcis_rule_3_1_8_name: "Ensure the maximum log file lifetime is set correctly"
  when:
    - postgresqlcis_rule_3_1_8
  tags:
    - postgresqlcis_rule_3_1_8

- name: "SECTION | {{ postgresqlcis_rule_3_1_9_id }} | {{ postgresqlcis_rule_3_1_9_name }}"
  ansible.builtin.include_tasks: cis_3.1.9.yml
  vars:
    postgresqlcis_rule_3_1_9_name: "Ensure the maximum log file size is set correctly"
  when:
    - postgresqlcis_rule_3_1_9
  tags:
    - postgresqlcis_rule_3_1_9

- name: "SECTION | {{ postgresqlcis_rule_3_1_10_id }} | {{ postgresqlcis_rule_3_1_10_name }}"
  ansible.builtin.include_tasks: cis_3.1.10.yml
  vars:
    postgresqlcis_rule_3_1_10_name: "Ensure the correct syslog facility is selected"
  when:
    - postgresqlcis_rule_3_1_10
  tags:
    - postgresqlcis_rule_3_1_10

- name: "SECTION | {{ postgresqlcis_rule_3_1_11_id }} | {{ postgresqlcis_rule_3_1_11_name }}"
  ansible.builtin.include_tasks: cis_3.1.11.yml
  vars:
    postgresqlcis_rule_3_1_11_name: "Ensure syslog messages are not suppressed"
  when:
    - postgresqlcis_rule_3_1_11
  tags:
    - postgresqlcis_rule_3_1_11

- name: "SECTION | {{ postgresqlcis_rule_3_1_12_id }} | {{ postgresqlcis_rule_3_1_12_name }}"
  ansible.builtin.include_tasks: cis_3.1.12.yml
  vars:
    postgresqlcis_rule_3_1_12_name: "Ensure syslog messages are not lost due to size"
  when:
    - postgresqlcis_rule_3_1_12
  tags:
    - postgresqlcis_rule_3_1_12

- name: "SECTION | {{ postgresqlcis_rule_3_1_13_id }} | {{ postgresqlcis_rule_3_1_13_name }}"
  ansible.builtin.include_tasks: cis_3.1.13.yml
  vars:
    postgresqlcis_rule_3_1_13_name: ""
  when:
    - postgresqlcis_rule_3_1_13
  tags:
    - postgresqlcis_rule_3_1_13

- name: "SECTION | {{ postgresqlcis_rule_3_1_14_id }} | {{ postgresqlcis_rule_3_1_14_name }}"
  ansible.builtin.include_tasks: cis_3.1.14.yml
  vars:
    postgresqlcis_rule_3_1_14_name: ""
  when:
    - postgresqlcis_rule_3_1_14
  tags:
    - postgresqlcis_rule_3_1_14

- name: "SECTION | {{ postgresqlcis_rule_3_1_15_id }} | {{ postgresqlcis_rule_3_1_15_name }}"
  ansible.builtin.include_tasks: cis_3.1.15.yml
  vars:
    postgresqlcis_rule_3_1_15_name: ""
  when:
    - postgresqlcis_rule_3_1_15
  tags:
    - postgresqlcis_rule_3_1_15

- name: "SECTION | {{ postgresqlcis_rule_3_1_16_id }} | {{ postgresqlcis_rule_3_1_16_name }}"
  ansible.builtin.include_tasks: cis_3.1.16.yml
  vars:
    postgresqlcis_rule_3_1_16_name: ""
  when:
    - postgresqlcis_rule_3_1_16
  tags:
    - postgresqlcis_rule_3_1_16

- name: "SECTION | {{ postgresqlcis_rule_3_1_17_id }} | {{ postgresqlcis_rule_3_1_17_name }}"
  ansible.builtin.include_tasks: cis_3.1.17.yml
  vars:
    postgresqlcis_rule_3_1_17_name: ""
  when:
    - postgresqlcis_rule_3_1_17
  tags:
    - postgresqlcis_rule_3_1_17

- name: "SECTION | {{ postgresqlcis_rule_3_1_18_id }} | {{ postgresqlcis_rule_3_1_18_name }}"
  ansible.builtin.include_tasks: cis_3.1.18.yml
  vars:
    postgresqlcis_rule_3_1_18_name: ""
  when:
    - postgresqlcis_rule_3_1_18
  tags:
    - postgresqlcis_rule_3_1_18

- name: "SECTION | {{ postgresqlcis_rule_3_1_19_id }} | {{ postgresqlcis_rule_3_1_19_name }}"
  ansible.builtin.include_tasks: cis_3.1.1.yml
  vars:
    postgresqlcis_rule_3_1_19_name: ""
  when:
    - postgresqlcis_rule_3_1_19
  tags:
    - postgresqlcis_rule_3_1_19

- name: "SECTION | {{ postgresqlcis_rule_3_1_20_id }} | {{ postgresqlcis_rule_3_1_20_name }}"
  ansible.builtin.include_tasks: cis_3.1.20.yml
  vars:
    postgresqlcis_rule_3_1_20_name: ""
  when:
    - postgresqlcis_rule_3_1_20
  tags:
    - postgresqlcis_rule_3_1_20

- name: "SECTION | {{ postgresqlcis_rule_3_1_21_id }} | {{ postgresqlcis_rule_3_1_21_name }}"
  ansible.builtin.include_tasks: cis_3.1.21.yml
  vars:
    postgresqlcis_rule_3_1_21_name: ""
  when:
    - postgresqlcis_rule_3_1_21
  tags:
    - postgresqlcis_rule_3_1_21

- name: "SECTION | {{ postgresqlcis_rule_3_1_22_id }} | {{ postgresqlcis_rule_3_1_22_name }}"
  ansible.builtin.include_tasks: cis_3.1.22.yml
  vars:
    postgresqlcis_rule_3_1_22_name: ""
  when:
    - postgresqlcis_rule_3_1_22
  tags:
    - postgresqlcis_rule_3_1_22

- name: "SECTION | {{ postgresqlcis_rule_3_1_23_id }} | {{ postgresqlcis_rule_3_1_23_name }}"
  ansible.builtin.include_tasks: cis_3.1.23.yml
  vars:
    postgresqlcis_rule_3_1_23_name: ""
  when:
    - postgresqlcis_rule_3_1_23
  tags:
    - postgresqlcis_rule_3_1_23

- name: "SECTION | {{ postgresqlcis_rule_3_1_24_id }} | {{ postgresqlcis_rule_3_1_24_name }}"
  ansible.builtin.include_tasks: cis_3.1.24.yml
  vars:
    postgresqlcis_rule_3_1_24_name: ""
  when:
    - postgresqlcis_rule_3_1_24
  tags:
    - postgresqlcis_rule_3_1_24

- name: "SECTION | {{ postgresqlcis_rule_3_1_25_id }} | {{ postgresqlcis_rule_3_1_25_name }}"
  ansible.builtin.include_tasks: cis_3.1.25.yml
  vars:
    postgresqlcis_rule_3_1_25_name: ""
  when:
    - postgresqlcis_rule_3_1_25
  tags:
    - postgresqlcis_rule_3_1_25

- name: "SECTION | {{ postgresqlcis_rule_3_1_26_id }} | {{ postgresqlcis_rule_3_1_26_name }}"
  ansible.builtin.include_tasks: cis_3.1.26.yml
  vars:
    postgresqlcis_rule_3_1_26_name: ""
  when:
    - postgresqlcis_rule_3_1_26
  tags:
    - postgresqlcis_rule_3_1_26

- name: "SECTION | {{ postgresqlcis_rule_3_2_id }} | {{ postgresqlcis_rule_3_2_name }}"
  ansible.builtin.include_tasks: cis_3.2.yml
  vars:
    postgresqlcis_rule_3_2_name: ""
  when:
    - postgresqlcis_rule_3_2
  tags:
    - postgresqlcis_rule_3_2
...
